# Generated by Django 2.0.6 on 2019-05-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'choose',
            },
        ),
    ]
