# Generated by Django 2.0.6 on 2019-05-17 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_chouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chouse',
            name='userid',
            field=models.ForeignKey(blank=True, db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='login.User', verbose_name='userid'),
        ),
    ]
