# Generated by Django 2.0.6 on 2019-05-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockCodeTXinlang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('positions', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'stock_code_t_xinlang',
                'managed': False,
            },
        ),
    ]
